---
title: "amazon_prime_transmutation"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(knitr)
read_chunk('shared_functions.R')
```

```{r child = 'amazon_originals.Rmd'}
```

## Transmutation of the given Amazon Prime series and movie table

```{r code = readlines("shared_functions.R")}
amazon_originals <- filter(amazon_originals,
                            !grepl("Pending|pending", Title),
                            Title != "Awaiting release",
                            !grepl("Miniseries|miniseries", Title),
                            !grepl("Renewed|renewed", Title),
                            !grepl("due to premiere", Title))

amazon_originals

amazon <- transmute(amazon_originals, 
                                Title = Title,
                                Genre = genres_to_uppercase(str_replace_all(
                                          str_squish(
                                            str_replace_all(
                                              str_replace_all(
                                                str_replace_all(
                                                  str_replace_all(
                                                    str_replace_all(Genre, "series|procedural", ""),
                                                  "Science fiction", "Science-Fiction"),
                                                "(C|c)oming-of-age ", ""),
                                              "(C|c)omedy-(D|d)rama", "Dramedy"),
                                            "(Docu|docu).*", "Documentary")
                                          ),
                                        "/| ", " / ")),
                                Premiere = as.Date(str_replace_all(str_replace_all(Premiere, ",", ""), " ", "-"), "%B-%d-%Y"),
                                Episodes = strtoi(ifelse(!is.na(str_match(Seasons, "([0-9]+) (episode*)")[,2]),
                                                  str_match(Seasons, "([0-9]+) (episode*)")[,2],
                                                  NA)),
                                Seasons = strtoi(ifelse(!is.na(str_match(Seasons, "([0-9]) (season.*|part.*|volume.*)")[,2]),
                                                  str_match(Seasons, "([0-9]) (season.*|part.*|volume.*)")[,2],
                                                  NA)),
                                Min_Time = strtoi(ifelse(!is.na(str_match(Runtime, "([0-9]+)-([0-9]+)")[,2]),
                                                  str_match(Runtime, "([0-9]+)-([0-9]+)")[,2],
                                                  str_match(Runtime, "([0-9]+)")[,2])),
                                Max_Time = strtoi(ifelse(!is.na(str_match(Runtime, "([0-9]+)-([0-9]+)")[,3]),
                                                  str_match(Runtime, "([0-9]+)-([0-9]+)")[,3],
                                                  str_match(Runtime, "([0-9]+)")[,2])),
                                Language = Language,
                                Status = Status,
                                Service = Service,
                                Format = as.factor(Format),
                                Origin = as.factor(Origin),
                                Network = as.factor(Network),
                                Region = as.factor(Region)
                               )

amazon
```