---
title: "amazon_originals"
author: "grevend"
date: "13 12 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(forcats)
```

```{r}
only_keep <- function(row, regex) {
  return(ifelse(!is.na(str_match(row, regex)[,2]), str_match(row, regex)[,2], str_match(row, regex)[,2]))
}

statuses <- c("Renewed", "Pending", "Miniseries", "Awaiting release", "Event", "Development", "Ended", "Film", "Special", "Distribution")

formats <- c("Series", "Miniseries", "Film", "Special")

origins <- c("Continuation", "Distribution", "Original")

services <- c("Netflix", "Amazon Prime Video", "Hulu", "Disney+", "Apple TV+")
```

## CSV import


```{r}
amazon_originals_1 <- read_csv("../datasets/amazon/shows/table-1.csv")
amazon_originals_1 <- transmute(amazon_originals_1,
                                Title = Title,
                                Genre = paste(Genre, " Drama"),
                                Premiere = Premiere,
                                Seasons = Seasons,
                                Runtime = NA,
                                Language = NA,
                                Status = Status,
                                Format = "Series",
                                Origin = "Original",
                                Network = NA,
                                Region = NA)

amazon_originals_2 <- read_csv("../datasets/amazon/shows/table-2.csv")
amazon_originals_2 <- transmute(amazon_originals_2,
                                Title = Title,
                                Genre = paste(Genre, " Comedy"),
                                Premiere = Premiere,
                                Seasons = Seasons,
                                Runtime = NA,
                                Language = NA,
                                Status = Status,
                                Format = "Series",
                                Origin = "Original",
                                Network = NA,
                                Region = NA)

amazon_originals_3 <- read_csv("../datasets/amazon/shows/table-3.csv")
amazon_originals_3 <- transmute(amazon_originals_3,
                                Title = Title,
                                Genre = paste(Genre, " Adult Animation"),
                                Premiere = Premiere,
                                Seasons = Seasons,
                                Runtime = NA,
                                Language = NA,
                                Status = Status,
                                Format = "Series",
                                Origin = "Original",
                                Network = NA,
                                Region = NA)

amazon_originals_4 <- read_csv("../datasets/amazon/shows/table-4.csv")
amazon_originals_4 <- transmute(amazon_originals_4,
                                Title = Title,
                                Genre = paste(Genre, " Kids Family Children Animation"),
                                Premiere = Premiere,
                                Seasons = `Seasons/episodes`,
                                Runtime = NA,
                                Language = NA,
                                Status = Status,
                                Format = "Series",
                                Origin = "Original",
                                Network = NA,
                                Region = NA)

amazon_originals_5 <- read_csv("../datasets/amazon/shows/table-5.csv")
amazon_originals_5 <- transmute(amazon_originals_5,
                                Title = Title,
                                Genre = paste(Genre, " Anime Animation"),
                                Premiere = Premiere,
                                Seasons = `Seasons/episodes`,
                                Runtime = NA,
                                Language = NA,
                                Status = Status,
                                Format = "Series",
                                Origin = "Original",
                                Network = NA,
                                Region = NA)

amazon_originals_6 <- read_csv("../datasets/amazon/shows/table-6.csv")
amazon_originals_6 <- transmute(amazon_originals_6,
                                Title = Title,
                                Genre = Genre,
                                Premiere = Premiere,
                                Seasons = `Seasons/episodes`,
                                Runtime = NA,
                                Language = "German",
                                Status = Status,
                                Format = "Series",
                                Origin = "Original",
                                Network = NA,
                                Region = NA)

amazon_originals_7 <- read_csv("../datasets/amazon/shows/table-7.csv")
amazon_originals_7 <- transmute(amazon_originals_7,
                                Title = Title,
                                Genre = Genre,
                                Premiere = Premiere,
                                Seasons = `Seasons/episodes`,
                                Runtime = NA,
                                Language = "Hindi",
                                Status = Status,
                                Format = "Series",
                                Origin = "Original",
                                Network = NA,
                                Region = NA)

amazon_originals_8 <- read_csv("../datasets/amazon/shows/table-8.csv")
amazon_originals_8 <- transmute(amazon_originals_8,
                                Title = Title,
                                Genre = Genre,
                                Premiere = Premiere,
                                Seasons = `Seasons/episodes`,
                                Runtime = NA,
                                Language = "Japanese",
                                Status = Status,
                                Format = "Series",
                                Origin = "Original",
                                Network = NA,
                                Region = NA)

amazon_originals_9 <- read_csv("../datasets/amazon/shows/table-9.csv")
amazon_originals_9 <- transmute(amazon_originals_9,
                                Title = Title,
                                Genre = Genre,
                                Premiere = Premiere,
                                Seasons = `Seasons/episodes`,
                                Runtime = NA,
                                Language = "Spanish",
                                Status = Status,
                                Format = "Series",
                                Origin = "Original",
                                Network = NA,
                                Region = NA)

amazon_originals_10 <- read_csv("../datasets/amazon/shows/table-10.csv")
amazon_originals_10 <- transmute(amazon_originals_10,
                                 Title = Title,
                                 Genre = Genre,
                                 Premiere = Premiere,
                                 Seasons = `Seasons/episodes`,
                                 Runtime = NA,
                                 Language = Language,
                                 Status = Status,
                                 Format = "Series",
                                 Origin = "Original",
                                 Network = NA,
                                 Region = NA)

amazon_originals_11 <- read_csv("../datasets/amazon/shows/table-11.csv")
amazon_originals_11 <- transmute(amazon_originals_11,
                                 Title = Title,
                                 Genre = paste(Genre, " Docuseries Unscripted"),
                                 Premiere = Premiere,
                                 Seasons = `Seasons/episodes`,
                                 Runtime = NA,
                                 Language = Language,
                                 Status = Status,
                                 Format = "Series",
                                 Origin = "Original",
                                 Network = NA,
                                 Region = NA)

amazon_originals_12 <- read_csv("../datasets/amazon/shows/table-12.csv")
amazon_originals_12 <- transmute(amazon_originals_12,
                                 Title = Title,
                                 Genre = paste(Genre, " Reality Unscripted"),
                                 Premiere = Premiere,
                                 Seasons = `Seasons/episodes`,
                                 Runtime = NA,
                                 Language = Language,
                                 Status = Status,
                                 Format = "Series",
                                 Origin = "Original",
                                 Network = NA,
                                 Region = NA)

amazon_originals_13 <- read_csv("../datasets/amazon/shows/table-13.csv")
amazon_originals_13 <- transmute(amazon_originals_13,
                                 Title = Title,
                                 Genre = paste(Genre, " Variety Unscripted"),
                                 Premiere = Premiere,
                                 Seasons = `Seasons/episodes`,
                                 Runtime = NA,
                                 Language = Language,
                                 Status = Status,
                                 Format = "Series",
                                 Origin = "Original",
                                 Network = NA,
                                 Region = NA)

amazon_originals_14 <- read_csv("../datasets/amazon/shows/table-14.csv")
amazon_originals_14 <- transmute(amazon_originals_14,
                                 Title = Title,
                                 Genre = Genre,
                                 Premiere = Premiere,
                                 Seasons = `Seasons/episodes`,
                                 Runtime = NA,
                                 Language = Language,
                                 Status = Status,
                                 Format = "Series",
                                 Origin = "Original",
                                 Network = Partner,
                                 Region = NA)

amazon_originals_15 <- read_csv("../datasets/amazon/shows/table-15.csv")
amazon_originals_15 <- transmute(amazon_originals_15,
                                 Title = Title,
                                 Genre = Genre,
                                 Premiere = Premiere,
                                 Seasons = `Seasons/episodes`,
                                 Runtime = NA,
                                 Language = Language,
                                 Status = Status,
                                 Format = "Series",
                                 Origin = "Continuation",
                                 Network = `Previous channel`,
                                 Region = `Prime Video exclusive region`)

amazon_originals_16 <- read_csv("../datasets/amazon/shows/table-16.csv")
amazon_originals_16 <- transmute(amazon_originals_16,
                                 Title = Title,
                                 Genre = Genre,
                                 Premiere = Premiere,
                                 Seasons = Seasons,
                                 Runtime = NA,
                                 Language = NA,
                                 Status = "Pending",
                                 Format = "Series",
                                 Origin = "Original",
                                 Network = NA,
                                 Region = NA)

amazon_originals_17 <- read_csv("../datasets/amazon/shows/table-17.csv")
amazon_originals_17 <- transmute(amazon_originals_17,
                                 Title = Title,
                                 Genre = Genre,
                                 Premiere = Premiere,
                                 Seasons = Seasons,
                                 Runtime = NA,
                                 Language = Language,
                                 Status = "Pending",
                                 Format = "Series",
                                 Origin = "Continuation",
                                 Network = `Previous channel`,
                                 Region = `Prime Video exclusive region`)

amazon_originals_18 <- read_csv("../datasets/amazon/shows/table-18.csv")
amazon_originals_18 <- transmute(amazon_originals_18,
                                 Title = Title,
                                 Genre = Genre,
                                 Premiere = NA,
                                 Seasons = NA,
                                 Runtime = NA,
                                 Language = NA,
                                 Status = "Development",
                                 Format = "Series",
                                 Origin = "Original",
                                 Network = NA,
                                 Region = NA)

amazon_originals_19 <- read_csv("../datasets/amazon/shows/table-19.csv")
amazon_originals_19 <- transmute(amazon_originals_19,
                                 Title = Title,
                                 Genre = paste(Genre, " Drama"),
                                 Premiere = `Original run`,
                                 Seasons = Seasons,
                                 Runtime = NA,
                                 Language = NA,
                                 Status = "Ended",
                                 Format = "Series",
                                 Origin = "Distribution",
                                 Network = `Original broadcaster`,
                                 Region = `Prime Video exclusive region`)

amazon_originals_20 <- read_csv("../datasets/amazon/shows/table-20.csv")
amazon_originals_20 <- transmute(amazon_originals_20,
                                 Title = Title,
                                 Genre = paste(Genre, " Comedy"),
                                 Premiere = `Original run`,
                                 Seasons = Seasons,
                                 Runtime = NA,
                                 Language = NA,
                                 Status = "Ended",
                                 Format = "Series",
                                 Origin = "Distribution",
                                 Network = `Original broadcaster`,
                                 Region = `Prime Video exclusive region`)

amazon_originals_21 <- read_csv("../datasets/amazon/shows/table-21.csv")
amazon_originals_21 <- transmute(amazon_originals_21,
                                 Title = Title,
                                 Genre = paste(Genre, " Animation"),
                                 Premiere = `Original run`,
                                 Seasons = Seasons,
                                 Runtime = NA,
                                 Language = Language,
                                 Status = "Ended",
                                 Format = "Series",
                                 Origin = "Distribution",
                                 Network = `Original broadcaster`,
                                 Region = `Prime Video exclusive region`)

amazon_originals_22 <- read_csv("../datasets/amazon/shows/table-22.csv")
amazon_originals_22 <- transmute(amazon_originals_22,
                                 Title = Title,
                                 Genre = paste(Genre, " Anime"),
                                 Premiere = `Original run`,
                                 Seasons = Seasons,
                                 Runtime = NA,
                                 Language = Language,
                                 Status = "Ended",
                                 Format = "Series",
                                 Origin = "Distribution",
                                 Network = `Original broadcaster`,
                                 Region = `Prime Video exclusive region`)

amazon_originals_23 <- read_csv("../datasets/amazon/shows/table-23.csv")
amazon_originals_23 <- transmute(amazon_originals_23,
                                 Title = Title,
                                 Genre = Genre,
                                 Premiere = `Original run`,
                                 Seasons = Seasons,
                                 Runtime = NA,
                                 Language = Language,
                                 Status = "Ended",
                                 Format = "Series",
                                 Origin = "Distribution",
                                 Network = `Original broadcaster`,
                                 Region = `Prime Video exclusive region`)

amazon_originals_24 <- read_csv("../datasets/amazon/shows/table-24.csv")
amazon_originals_24 <- transmute(amazon_originals_24,
                                 Title = Title,
                                 Genre = Genre,
                                 Premiere = `Original run`,
                                 Seasons = `Seasons/episodes`,
                                 Runtime = NA,
                                 Language = Language,
                                 Status = "Ended",
                                 Format = "Series",
                                 Origin = "Continuation",
                                 Network = `Original network`,
                                 Region = `Prime Video exclusive region`)

amazon_originals <- rbind(amazon_originals_1, amazon_originals_2)
amazon_originals <- rbind(amazon_originals, amazon_originals_3)
amazon_originals <- rbind(amazon_originals, amazon_originals_4)
amazon_originals <- rbind(amazon_originals, amazon_originals_5)
amazon_originals <- rbind(amazon_originals, amazon_originals_6)
amazon_originals <- rbind(amazon_originals, amazon_originals_7)
amazon_originals <- rbind(amazon_originals, amazon_originals_8)
amazon_originals <- rbind(amazon_originals, amazon_originals_9)
amazon_originals <- rbind(amazon_originals, amazon_originals_10)
amazon_originals <- rbind(amazon_originals, amazon_originals_11)
amazon_originals <- rbind(amazon_originals, amazon_originals_12)
amazon_originals <- rbind(amazon_originals, amazon_originals_13)
amazon_originals <- rbind(amazon_originals, amazon_originals_14)
amazon_originals <- rbind(amazon_originals, amazon_originals_15)
amazon_originals <- rbind(amazon_originals, amazon_originals_16)
amazon_originals <- rbind(amazon_originals, amazon_originals_17)
amazon_originals <- rbind(amazon_originals, amazon_originals_18)
amazon_originals <- rbind(amazon_originals, amazon_originals_19)
amazon_originals <- rbind(amazon_originals, amazon_originals_20)
amazon_originals <- rbind(amazon_originals, amazon_originals_21)
amazon_originals <- rbind(amazon_originals, amazon_originals_22)
amazon_originals <- rbind(amazon_originals, amazon_originals_23)
amazon_originals <- rbind(amazon_originals, amazon_originals_24)

unique(select(amazon_originals, Status))

amazon_originals <- transmute(amazon_originals, 
                              Title = Title,
                              Genre = Genre,
                              Premiere = Premiere,
                              Seasons = Seasons,
                              Runtime = Runtime,
                              Language = Language,
                              Status = parse_factor(only_keep(Status, "(Renewed|Pending|Miniseries|Awaiting release|Event|Development|Ended|Film|Special|Distribution)"), levels = statuses),
                              Service = parse_factor("Amazon Prime Video", levels = services),
                              Format = parse_factor(only_keep(Format, "(Series|Miniseries|Film|Special)"), levels = formats),
                              Origin = parse_factor(only_keep(Origin, "(Continuation|Distribution|Original)"), levels = origins),
                              Network = Network,
                              Region = Region)

amazon_originals
```