---
title: "apple_originals"
author: "grevend"
date: "31 12 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(forcats)
```

```{r}
only_keep <- function(row, regex) {
  return(ifelse(!is.na(str_match(row, regex)[,2]), str_match(row, regex)[,2], str_match(row, regex)[,2]))
}

statuses <- c("Renewed", "Pending", "Miniseries", "Awaiting release", "Event", "Development", "Ended", "Film", "Special", "Distribution")

formats <- c("Series", "Miniseries", "Film", "Special")

origins <- c("Continuation", "Distribution", "Original")

services <- c("Netflix", "Amazon Prime Video", "Hulu", "Disney+", "Apple TV+")
```

## CSV import

```{r}
apple_originals_1 <- read_csv("../datasets/apple/shows/table-1.csv")
apple_originals_1 <- transmute(apple_originals_1,
                               Title = Title,
                               Genre = paste(Genre, " Drama"),
                               Premiere = Premiere,
                               Seasons = Seasons,
                               Runtime = Runtime,
                               Language = NA,
                               Status = Status,
                               Format = "Series",
                               Origin = "Original",
                               Network = NA,
                               Region = NA)

apple_originals_2 <- read_csv("../datasets/apple/shows/table-2.csv")
apple_originals_2 <- transmute(apple_originals_2,
                               Title = Title,
                               Genre = paste(Genre, " Comedy"),
                               Premiere = Premiere,
                               Seasons = Seasons,
                               Runtime = Runtime,
                               Language = NA,
                               Status = Status,
                               Format = "Series",
                               Origin = "Original",
                               Network = NA,
                               Region = NA)

apple_originals_3 <- read_csv("../datasets/apple/shows/table-3.csv")
apple_originals_3 <- transmute(apple_originals_3,
                               Title = Title,
                               Genre = paste(Genre, " Adult Animation"),
                               Premiere = Premiere,
                               Seasons = Seasons,
                               Runtime = Runtime,
                               Language = NA,
                               Status = Status,
                               Format = "Series",
                               Origin = "Original",
                               Network = NA,
                               Region = NA)

apple_originals_4 <- read_csv("../datasets/apple/shows/table-4.csv")
apple_originals_4 <- transmute(apple_originals_4,
                               Title = Title,
                               Genre = paste(Genre, " Kids Family Children"),
                               Premiere = Premiere,
                               Seasons = Seasons,
                               Runtime = Runtime,
                               Language = NA,
                               Status = Status,
                               Format = "Series",
                               Origin = "Original",
                               Network = NA,
                               Region = NA)

apple_originals_5 <- read_csv("../datasets/apple/shows/table-5.csv")
apple_originals_5 <- transmute(apple_originals_5,
                               Title = Title,
                               Genre = paste(Genre, " Docuseries Unscripted"),
                               Premiere = Premiere,
                               Seasons = Seasons,
                               Runtime = Runtime,
                               Language = NA,
                               Status = Status,
                               Format = "Series",
                               Origin = "Original",
                               Network = NA,
                               Region = NA)

apple_originals_6 <- read_csv("../datasets/apple/shows/table-6.csv")
apple_originals_6 <- transmute(apple_originals_6,
                               Title = Title,
                               Genre = paste(Genre, " Variety Unscripted"),
                               Premiere = Premiere,
                               Seasons = Seasons,
                               Runtime = Runtime,
                               Language = NA,
                               Status = Status,
                               Format = "Series",
                               Origin = "Original",
                               Network = NA,
                               Region = NA)

apple_originals_7 <- read_csv("../datasets/apple/shows/table-7.csv")
apple_originals_7 <- transmute(apple_originals_7,
                               Title = Title,
                               Genre = Genre,
                               Premiere = Premiere,
                               Seasons = Seasons,
                               Runtime = Runtime,
                               Language = NA,
                               Status = Status,
                               Format = "Series",
                               Origin = "Original",
                               Network = `Partner/Country`,
                               Region = `Partner/Country`)

apple_originals_8 <- read_csv("../datasets/apple/shows/table-8.csv")
apple_originals_8 <- transmute(apple_originals_8,
                               Title = Title,
                               Genre = paste(Genre, " Drama"),
                               Premiere = Premiere,
                               Seasons = Seasons,
                               Runtime = Runtime,
                               Language = NA,
                               Status = "Pending",
                               Format = "Series",
                               Origin = "Original",
                               Network = NA,
                               Region = NA)

apple_originals_9 <- read_csv("../datasets/apple/shows/table-9.csv")
apple_originals_9 <- transmute(apple_originals_9,
                               Title = Title,
                               Genre = paste(Genre, " Comedy"),
                               Premiere = Premiere,
                               Seasons = Seasons,
                               Runtime = Runtime,
                               Language = NA,
                               Status = "Pending",
                               Format = "Series",
                               Origin = "Original",
                               Network = NA,
                               Region = NA)

apple_originals_10 <- read_csv("../datasets/apple/shows/table-10.csv")
apple_originals_10 <- transmute(apple_originals_10,
                                Title = Title,
                                Genre = paste(Genre, " Kids Family Children Animation"),
                                Premiere = Premiere,
                                Seasons = Seasons,
                                Runtime = Runtime,
                                Language = NA,
                                Status = "Pending",
                                Format = "Series",
                                Origin = "Original",
                                Network = NA,
                                Region = NA)

apple_originals_11 <- read_csv("../datasets/apple/shows/table-11.csv")
apple_originals_11 <- transmute(apple_originals_11,
                                Title = Title,
                                Genre = paste(Genre, " Docuseries Unscripted"),
                                Premiere = Premiere,
                                Seasons = Seasons,
                                Runtime = Runtime,
                                Language = NA,
                                Status = "Pending",
                                Format = "Series",
                                Origin = "Original",
                                Network = NA,
                                Region = NA)

apple_originals_12 <- read_csv("../datasets/apple/shows/table-12.csv")
apple_originals_12 <- transmute(apple_originals_12,
                                Title = Title,
                                Genre = paste(Genre, " Reality Unscripted"),
                                Premiere = Premiere,
                                Seasons = Seasons,
                                Runtime = Runtime,
                                Language = NA,
                                Status = "Pending",
                                Format = "Series",
                                Origin = "Original",
                                Network = NA,
                                Region = NA)

apple_originals_13 <- read_csv("../datasets/apple/shows/table-13.csv")
apple_originals_13 <- transmute(apple_originals_13,
                                Title = Title,
                                Genre = paste(Genre, " Variety Unscripted"),
                                Premiere = Premiere,
                                Seasons = Seasons,
                                Runtime = Runtime,
                                Language = NA,
                                Status = "Pending",
                                Format = "Series",
                                Origin = "Original",
                                Network = NA,
                                Region = NA)

apple_originals_14 <- read_csv("../datasets/apple/shows/table-14.csv")
apple_originals_14 <- transmute(apple_originals_14,
                                Title = Title,
                                Genre = Genre,
                                Premiere = Premiere,
                                Seasons = Seasons,
                                Runtime = Runtime,
                                Language = NA,
                                Status = "Pending",
                                Format = "Series",
                                Origin = "Original",
                                Network = `Partner/Country`,
                                Region = `Partner/Country`)

apple_originals_15 <- read_csv("../datasets/apple/shows/table-15.csv")
apple_originals_15 <- transmute(apple_originals_15,
                                Title = Title,
                                Genre = Genre,
                                Premiere = NA,
                                Seasons = NA,
                                Runtime = NA,
                                Language = NA,
                                Status = "Development",
                                Format = "Series",
                                Origin = "Original",
                                Network = NA,
                                Region = NA)

apple_originals_16 <- read_csv("../datasets/apple/films/table-1.csv")
apple_originals_16 <- transmute(apple_originals_16,
                                Title = Title,
                                Genre = Genre,
                                Premiere = Release,
                                Seasons = NA,
                                Runtime = Runtime,
                                Language = NA,
                                Status = "Ended",
                                Format = "Film",
                                Origin = "Original",
                                Network = NA,
                                Region = NA)

apple_originals_17 <- read_csv("../datasets/apple/films/table-2.csv")
apple_originals_17 <- transmute(apple_originals_17,
                                Title = Title,
                                Genre = paste(Genre, " Documentary"),
                                Premiere = Release,
                                Seasons = NA,
                                Runtime = Runtime,
                                Language = NA,
                                Status = ifelse(str_detect(Runtime, "TBA"), "Pending", "Ended"),
                                Format = "Film",
                                Origin = "Original",
                                Network = NA,
                                Region = NA)

apple_originals_18 <- read_csv("../datasets/apple/films/table-3.csv")
apple_originals_18 <- transmute(apple_originals_18,
                                Title = Title,
                                Genre = Genre,
                                Premiere = Release,
                                Seasons = NA,
                                Runtime = Runtime,
                                Language = NA,
                                Status = "Ended",
                                Format = "Special",
                                Origin = "Original",
                                Network = NA,
                                Region = NA)

apple_originals_19 <- read_csv("../datasets/apple/films/table-4.csv")
apple_originals_19 <- transmute(apple_originals_19,
                                Title = Title,
                                Genre = Genre,
                                Premiere = Release,
                                Seasons = NA,
                                Runtime = Runtime,
                                Language = NA,
                                Status = "Pending",
                                Format = "Film",
                                Origin = "Original",
                                Network = NA,
                                Region = NA)

apple_originals_20 <- read_csv("../datasets/apple/films/table-5.csv")
apple_originals_20 <- transmute(apple_originals_20,
                                Title = Title,
                                Genre = paste(Genre, " Documentary"),
                                Premiere = Release,
                                Seasons = NA,
                                Runtime = Runtime,
                                Language = NA,
                                Status = "Pending",
                                Format = "Film",
                                Origin = "Original",
                                Network = NA,
                                Region = NA)

apple_originals_21 <- read_csv("../datasets/apple/films/table-6.csv")
apple_originals_21 <- transmute(apple_originals_21,
                                Title = Title,
                                Genre = Genre,
                                Premiere = Release,
                                Seasons = NA,
                                Runtime = Length,
                                Language = NA,
                                Status = "Pending",
                                Format = "Special",
                                Origin = "Original",
                                Network = NA,
                                Region = NA)

apple_originals <- rbind(apple_originals_1, apple_originals_2)
apple_originals <- rbind(apple_originals, apple_originals_3)
apple_originals <- rbind(apple_originals, apple_originals_4)
apple_originals <- rbind(apple_originals, apple_originals_5)
apple_originals <- rbind(apple_originals, apple_originals_6)
apple_originals <- rbind(apple_originals, apple_originals_7)
apple_originals <- rbind(apple_originals, apple_originals_8)
apple_originals <- rbind(apple_originals, apple_originals_9)
apple_originals <- rbind(apple_originals, apple_originals_10)
apple_originals <- rbind(apple_originals, apple_originals_11)
apple_originals <- rbind(apple_originals, apple_originals_12)
apple_originals <- rbind(apple_originals, apple_originals_13)
apple_originals <- rbind(apple_originals, apple_originals_14)
apple_originals <- rbind(apple_originals, apple_originals_15)
apple_originals <- rbind(apple_originals, apple_originals_16)
apple_originals <- rbind(apple_originals, apple_originals_17)
apple_originals <- rbind(apple_originals, apple_originals_18)
apple_originals <- rbind(apple_originals, apple_originals_19)
apple_originals <- rbind(apple_originals, apple_originals_20)
apple_originals <- rbind(apple_originals, apple_originals_21)

unique(select(apple_originals, Status))

apple_originals <- transmute(apple_originals, 
                             Title = Title,
                             Genre = Genre,
                             Premiere = Premiere,
                             Seasons = Seasons,
                             Runtime = Runtime,
                             Language = Language,
                             Status = parse_factor(only_keep(Status, "(Renewed|Pending|Miniseries|Awaiting release|Event|Development|Ended|Film|Special|Distribution)"), levels = statuses),
                             Service = parse_factor("Apple TV+", levels = services),
                             Format = parse_factor(only_keep(Format, "(Series|Miniseries|Film|Special)"), levels = formats),
                             Origin = parse_factor(only_keep(Origin, "(Continuation|Distribution|Original)"), levels = origins),
                             Network = Network,
                             Region = Region)

apple_originals

rm(list = ls(pattern = "_originals_[0-9]+"))
```