---
title: "disney_originals"
author: "grevend"
date: "13 12 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(forcats)
```

```{r}
only_keep <- function(row, regex) {
  return(ifelse(!is.na(str_match(row, regex)[,2]), str_match(row, regex)[,2], str_match(row, regex)[,2]))
}

statuses <- c("Renewed", "Pending", "Miniseries", "Awaiting release", "Event", "Development", "Ended", "Film", "Special", "Distribution")

formats <- c("Series", "Miniseries", "Film", "Special")

origins <- c("Continuation", "Distribution", "Original")

services <- c("Netflix", "Amazon Prime Video", "Hulu", "Disney+", "Apple TV+")
```

## CSV import

```{r}

# Statuses = Renewed, Pending, Awaiting release, Ended, Special, Development
# Formats = Series, Miniseries, Film, Event
# Origin = Continuation, Distribution, Original

# old: Title, Genre, Premiere, Seasons, Runtime, Language, Status


# new: Title, Genre, Premiere, Seasons, Runtime, Language, Status, Format, Origin, Service, Network, Region

disney_originals_1 <- read_csv("../datasets/disney/shows/table-1.csv")
disney_originals_1 <- transmute(disney_originals_1,
                                Title = Title,
                                Genre = paste(Genre, " Drama"),
                                Premiere = Premiere,
                                Seasons = Seasons,
                                Runtime = Runtime,
                                Language = NA,
                                Status = Status,
                                Format = "Series",
                                Origin = "Original",
                                Network = NA,
                                Region = NA)

disney_originals_2 <- read_csv("../datasets/disney/shows/table-2.csv")
disney_originals_2 <- transmute(disney_originals_2,
                                Title = Title,
                                Genre = paste(Genre, " Comedy"),
                                Premiere = Premiere,
                                Seasons = Seasons,
                                Runtime = Runtime,
                                Language = NA,
                                Status = Status,
                                Format = "Series",
                                Origin = "Original",
                                Network = NA,
                                Region = NA)

disney_originals_3 <- read_csv("../datasets/disney/shows/table-3.csv")
disney_originals_3 <- transmute(disney_originals_3,
                                Title = Title,
                                Genre = paste(Genre, " Shorts"),
                                Premiere = Premiere,
                                Seasons = Seasons,
                                Runtime = Runtime,
                                Language = NA,
                                Status = Status,
                                Format = "Series",
                                Origin = "Original",
                                Network = NA,
                                Region = NA)

disney_originals_4 <- read_csv("../datasets/disney/shows/table-4.csv")
disney_originals_4 <- transmute(disney_originals_4,
                                Title = Title,
                                Genre = paste(Genre, " Docuseries Unscripted"),
                                Premiere = Premiere,
                                Seasons = Seasons,
                                Runtime = Runtime,
                                Language = NA,
                                Status = Status,
                                Format = "Series",
                                Origin = "Original",
                                Network = NA,
                                Region = NA)

disney_originals_5 <- read_csv("../datasets/disney/shows/table-5.csv")
disney_originals_5 <- transmute(disney_originals_5,
                                Title = Title,
                                Genre = paste(Genre, " Reality Unscripted"),
                                Premiere = Premiere,
                                Seasons = Seasons,
                                Runtime = Runtime,
                                Language = NA,
                                Status = Status,
                                Format = "Series",
                                Origin = "Original",
                                Network = NA,
                                Region = NA)

disney_originals_6 <- read_csv("../datasets/disney/shows/table-6.csv")
disney_originals_6 <- transmute(disney_originals_6,
                                Title = Title,
                                Genre = paste(Genre, " Variety Unscripted"),
                                Premiere = Premiere,
                                Seasons = Seasons,
                                Runtime = Runtime,
                                Language = NA,
                                Status = Status,
                                Format = "Series",
                                Origin = "Original",
                                Network = NA,
                                Region = NA)

disney_originals_7 <- read_csv("../datasets/disney/shows/table-7.csv")
disney_originals_7 <- transmute(disney_originals_7,
                                Title = Title,
                                Genre = Genre,
                                Premiere = Premiere,
                                Seasons = Seasons,
                                Runtime = Runtime,
                                Language = NA,
                                Status = Status,
                                Format = "Series",
                                Origin = "Continuation",
                                Network = Network,
                                Region = NA)

disney_originals_8 <- read_csv("../datasets/disney/shows/table-8.csv")
disney_originals_8 <- transmute(disney_originals_8,
                                Title = Title,
                                Genre = Genre,
                                Premiere = Premiere,
                                Seasons = NA,
                                Runtime = Runtime,
                                Language = NA,
                                Status = "Special",
                                Format = "Series",
                                Origin = "Original",
                                Network = NA,
                                Region = NA)

# missing exclusives
# missing table-9 content on wiki

disney_originals_10 <- read_csv("../datasets/disney/shows/table-10.csv")
disney_originals_10 <- transmute(disney_originals_10,
                                Title = Title,
                                Genre = Genre,
                                Premiere = Premiere,
                                Seasons = Seasons,
                                Runtime = Runtime,
                                Language = NA,
                                Status = Status,
                                Format = "Series",
                                Origin = "Original",
                                Network = NA,
                                Region = NA)

disney_originals_11 <- read_csv("../datasets/disney/shows/table-11.csv")
disney_originals_11 <- transmute(disney_originals_11,
                                Title = Title,
                                Genre = paste(Genre, " Drama"),
                                Premiere = Premiere,
                                Seasons = Seasons,
                                Runtime = Runtime,
                                Language = NA,
                                Status = Status,
                                Format = "Series",
                                Origin = "Original",
                                Network = NA,
                                Region = NA)

disney_originals_12 <- read_csv("../datasets/disney/shows/table-12.csv")
disney_originals_12 <- transmute(disney_originals_12,
                                Title = Title,
                                Genre = paste(Genre, " Comedy"),
                                Premiere = Premiere,
                                Seasons = Seasons,
                                Runtime = Runtime,
                                Language = NA,
                                Status = Status,
                                Format = "Series",
                                Origin = "Original",
                                Network = NA,
                                Region = NA)

disney_originals_13 <- read_csv("../datasets/disney/shows/table-13.csv")
disney_originals_13 <- transmute(disney_originals_13,
                                Title = Title,
                                Genre = paste(Genre, " Animation"),
                                Premiere = Premiere,
                                Seasons = Seasons,
                                Runtime = Runtime,
                                Language = NA,
                                Status = Status,
                                Format = "Series",
                                Origin = "Original",
                                Network = NA,
                                Region = NA)

disney_originals_14 <- read_csv("../datasets/disney/shows/table-14.csv")
disney_originals_14 <- transmute(disney_originals_14,
                                Title = Title,
                                Genre = paste(Genre, " Docuseries Unscripted"),
                                Premiere = Premiere,
                                Seasons = Seasons,
                                Runtime = Runtime,
                                Language = NA,
                                Status = Status,
                                Format = "Series",
                                Origin = "Original",
                                Network = NA,
                                Region = NA)

disney_originals_15 <- read_csv("../datasets/disney/shows/table-15.csv")
disney_originals_15 <- transmute(disney_originals_15,
                                Title = Title,
                                Genre = paste(Genre, " Reality Unscripted"),
                                Premiere = Premiere,
                                Seasons = Seasons,
                                Runtime = Runtime,
                                Language = NA,
                                Status = Status,
                                Format = "Series",
                                Origin = "Original",
                                Network = NA,
                                Region = NA)

disney_originals_16 <- read_csv("../datasets/disney/shows/table-16.csv")
disney_originals_16 <- transmute(disney_originals_16,
                                Title = Title,
                                Genre = Genre,
                                Premiere = Premiere,
                                Seasons = Seasons,
                                Runtime = Runtime,
                                Language = NA,
                                Status = Status,
                                Format = "Series",
                                Origin = "Continuation",
                                Network = `Prev. network(s)`,
                                Region = NA)

disney_originals_17 <- read_csv("../datasets/disney/shows/table-17.csv")
disney_originals_17 <- transmute(disney_originals_17,
                                Title = Title,
                                Genre = Genre,
                                Premiere = NA,
                                Seasons = NA,
                                Runtime = NA,
                                Language = NA,
                                Status = "Development",
                                Format = "Series",
                                Origin = "Original",
                                Network = NA,
                                Region = NA)

disney_originals_18 <- read_csv("../datasets/disney/films/table-1.csv")
disney_originals_18 <- transmute(disney_originals_18,
                                Title = Title,
                                Genre = Genre,
                                Premiere = `Release date`,
                                Seasons = NA,
                                Runtime = Runtime,
                                Language = NA,
                                Status = ifelse(str_detect(Runtime, "TBA"), "Pending", "Ended"),
                                Format = "Film",
                                Origin = "Original",
                                Network = NA,
                                Region = NA)

disney_originals_19 <- read_csv("../datasets/disney/films/table-2.csv")
disney_originals_19 <- transmute(disney_originals_19,
                                Title = Title,
                                Genre = Genre,
                                Premiere = `Release date`,
                                Seasons = NA,
                                Runtime = Runtime,
                                Language = NA,
                                Status = "Ended",
                                Format = "Film",
                                Origin = "Original",
                                Network = NA,
                                Region = NA)

disney_originals_20 <- read_csv("../datasets/disney/films/table-3.csv")
disney_originals_20 <- transmute(disney_originals_20,
                                Title = Title,
                                Genre = Genre,
                                Premiere = `Release date`,
                                Seasons = NA,
                                Runtime = Runtime,
                                Language = NA,
                                Status = ifelse(str_detect(Runtime, "TBA"), "Pending", "Ended"),
                                Format = "Film",
                                Origin = "Original",
                                Network = NA,
                                Region = NA)

disney_originals_21 <- read_csv("../datasets/disney/films/table-4.csv")
disney_originals_21 <- transmute(disney_originals_21,
                                Title = Title,
                                Genre = paste(Genre, " Documentary"),
                                Premiere = `Release date`,
                                Seasons = NA,
                                Runtime = Runtime,
                                Language = NA,
                                Status = "Ended",
                                Format = "Film",
                                Origin = "Original",
                                Network = NA,
                                Region = NA)

disney_originals_22 <- read_csv("../datasets/disney/films/table-5.csv")
disney_originals_22 <- transmute(disney_originals_22,
                                Title = Title,
                                Genre = Genre,
                                Premiere = `Release date`,
                                Seasons = NA,
                                Runtime = Runtime,
                                Language = NA,
                                Status = "Special",
                                Format = "Film",
                                Origin = "Original",
                                Network = NA,
                                Region = NA)

disney_originals_23 <- read_csv("../datasets/disney/films/table-6.csv")
disney_originals_23 <- transmute(disney_originals_23,
                                Title = Title,
                                Genre = paste(Genre, " Exclusive"),
                                Premiere = `Release date`,
                                Seasons = NA,
                                Runtime = Runtime,
                                Language = NA,
                                Status = "Ended",
                                Format = "Film",
                                Origin = "Distribution",
                                Network = NA,
                                Region = "France")

disney_originals_24 <- read_csv("../datasets/disney/films/table-7.csv")
disney_originals_24 <- transmute(disney_originals_24,
                                Title = Title,
                                Genre = Genre,
                                Premiere = `Release date`,
                                Seasons = NA,
                                Runtime = Runtime,
                                Language = NA,
                                Status = "Pending",
                                Format = "Film",
                                Origin = "Original",
                                Network = NA,
                                Region = NA)

disney_originals_25 <- read_csv("../datasets/disney/films/table-8.csv")
disney_originals_25 <- transmute(disney_originals_25,
                                Title = Title,
                                Genre = paste(Genre, " Documentary"),
                                Premiere = `Release date`,
                                Seasons = NA,
                                Runtime = Runtime,
                                Language = NA,
                                Status = "Pending",
                                Format = "Film",
                                Origin = "Original",
                                Network = NA,
                                Region = NA)

disney_originals_26 <- read_csv("../datasets/disney/films/table-9.csv")
disney_originals_26 <- transmute(disney_originals_26,
                                Title = Title,
                                Genre = Genre,
                                Premiere = `Release date`,
                                Seasons = NA,
                                Runtime = Runtime,
                                Language = NA,
                                Status = "Development",
                                Format = "Special",
                                Origin = "Original",
                                Network = NA,
                                Region = NA)

disney_originals_27 <- read_csv("../datasets/disney/films/table-10.csv")
disney_originals_27 <- transmute(disney_originals_27,
                                Title = Title,
                                Genre = Genre,
                                Premiere = NA,
                                Seasons = NA,
                                Runtime = NA,
                                Language = NA,
                                Status = "Development",
                                Format = "Film",
                                Origin = "Original",
                                Network = NA,
                                Region = NA)

disney_originals_28 <- read_csv("../datasets/disney/films/table-11.csv")
disney_originals_28 <- transmute(disney_originals_28,
                                Title = Title,
                                Genre = Genre,
                                Premiere = NA,
                                Seasons = NA,
                                Runtime = NA,
                                Language = NA,
                                Status = "Development",
                                Format = "Special",
                                Origin = "Original",
                                Network = NA,
                                Region = NA)

disney_originals <- rbind(disney_originals_1, disney_originals_2)
disney_originals <- rbind(disney_originals, disney_originals_3)
disney_originals <- rbind(disney_originals, disney_originals_4)
disney_originals <- rbind(disney_originals, disney_originals_5)
disney_originals <- rbind(disney_originals, disney_originals_6)
disney_originals <- rbind(disney_originals, disney_originals_7)
disney_originals <- rbind(disney_originals, disney_originals_8)
#disney_originals <- rbind(disney_originals, disney_originals_9)
disney_originals <- rbind(disney_originals, disney_originals_10)
disney_originals <- rbind(disney_originals, disney_originals_11)
disney_originals <- rbind(disney_originals, disney_originals_12)
disney_originals <- rbind(disney_originals, disney_originals_13)
disney_originals <- rbind(disney_originals, disney_originals_14)
disney_originals <- rbind(disney_originals, disney_originals_15)
disney_originals <- rbind(disney_originals, disney_originals_16)
disney_originals <- rbind(disney_originals, disney_originals_17)
disney_originals <- rbind(disney_originals, disney_originals_18)
disney_originals <- rbind(disney_originals, disney_originals_19)
disney_originals <- rbind(disney_originals, disney_originals_20)
disney_originals <- rbind(disney_originals, disney_originals_21)
disney_originals <- rbind(disney_originals, disney_originals_22)
disney_originals <- rbind(disney_originals, disney_originals_23)
disney_originals <- rbind(disney_originals, disney_originals_24)
disney_originals <- rbind(disney_originals, disney_originals_25)
disney_originals <- rbind(disney_originals, disney_originals_26)
disney_originals <- rbind(disney_originals, disney_originals_27)
disney_originals <- rbind(disney_originals, disney_originals_28)

unique(select(disney_originals, Status))

disney_originals <- transmute(disney_originals, 
                              Title = Title,
                              Genre = Genre,
                              Premiere = Premiere,
                              Seasons = Seasons,
                              Runtime = Runtime,
                              Language = Language,
                              Status = parse_factor(only_keep(Status, "(Renewed|Pending|Miniseries|Awaiting release|Event|Development|Ended|Film|Special|Distribution)"), levels = statuses),
                              Service = parse_factor("Disney+", levels = services),
                              Format = parse_factor(only_keep(Format, "(Series|Miniseries|Film|Special)"), levels = formats),
                              Origin = parse_factor(only_keep(Origin, "(Continuation|Distribution|Original)"), levels = origins),
                              Network = Network,
                              Region = Region)

disney_originals
```