---
title: "hulu_originals"
author: "grevend"
date: "13 12 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(forcats)
```

```{r}
only_keep <- function(row, regex) {
  return(ifelse(!is.na(str_match(row, regex)[,2]), str_match(row, regex)[,2], str_match(row, regex)[,2]))
}

statuses <- c("Renewed", "Pending", "Miniseries", "Awaiting release", "Event", "Development", "Ended", "Film", "Special", "Distribution")

formats <- c("Series", "Miniseries", "Film", "Special")

origins <- c("Continuation", "Distribution", "Original")

services <- c("Netflix", "Amazon Prime Video", "Hulu", "Disney+")
```

## CSV import

```{r}
hulu_originals_1 <- read_csv("../datasets/hulu/shows/table-1.csv")
hulu_originals_1 <- transmute(hulu_originals_1,
                              Title = Title,
                              Genre = paste(Genre, " Drama"),
                              Premiere = Premiere,
                              Seasons = Seasons,
                              Runtime = Length,
                              Language = NA,
                              Status = Status,
                              Format = "Series",
                              Origin = "Original",
                              Network = NA,
                              Region = NA)

hulu_originals_2 <- read_csv("../datasets/hulu/shows/table-2.csv")
hulu_originals_2 <- transmute(hulu_originals_2,
                              Title = Title,
                              Genre = paste(Genre, " Comedy"),
                              Premiere = Premiere,
                              Seasons = Seasons,
                              Runtime = Length,
                              Language = NA,
                              Status = Status,
                              Format = "Series",
                              Origin = "Original",
                              Network = NA,
                              Region = NA)

hulu_originals_3 <- read_csv("../datasets/hulu/shows/table-3.csv")
hulu_originals_3 <- transmute(hulu_originals_3,
                              Title = Title,
                              Genre = paste(Genre, " Adult Animation"),
                              Premiere = Premiere,
                              Seasons = Seasons,
                              Runtime = Length,
                              Language = NA,
                              Status = Status,
                              Format = "Series",
                              Origin = "Original",
                              Network = NA,
                              Region = NA)

hulu_originals_4 <- read_csv("../datasets/hulu/shows/table-4.csv")
hulu_originals_4 <- transmute(hulu_originals_4,
                              Title = Title,
                              Genre = paste(Genre, " Children Kids Family"),
                              Premiere = Premiere,
                              Seasons = Seasons,
                              Runtime = Length,
                              Language = NA,
                              Status = Status,
                              Format = "Series",
                              Origin = "Original",
                              Network = NA,
                              Region = NA)

hulu_originals_5 <- read_csv("../datasets/hulu/shows/table-5.csv")
hulu_originals_5 <- transmute(hulu_originals_5,
                              Title = Title,
                              Genre = paste(Genre, " Docu-series Unscripted"),
                              Premiere = Premiere,
                              Seasons = Seasons,
                              Runtime = Length,
                              Language = NA,
                              Status = Status,
                              Format = "Series",
                              Origin = "Original",
                              Network = NA,
                              Region = NA)

hulu_originals_6 <- read_csv("../datasets/hulu/shows/table-6.csv")
hulu_originals_6 <- transmute(hulu_originals_6,
                              Title = Title,
                              Genre = paste(Genre, " Reality Unscripted"),
                              Premiere = Premiere,
                              Seasons = Seasons,
                              Runtime = Length,
                              Language = NA,
                              Status = Status,
                              Format = "Series",
                              Origin = "Original",
                              Network = NA,
                              Region = NA)

hulu_originals_7 <- read_csv("../datasets/hulu/shows/table-7.csv")
hulu_originals_7 <- transmute(hulu_originals_7,
                              Title = Title,
                              Genre = paste(Genre, " Variety Unscripted"),
                              Premiere = Premiere,
                              Seasons = Seasons,
                              Runtime = Length,
                              Language = NA,
                              Status = Status,
                              Format = "Series",
                              Origin = "Original",
                              Network = NA,
                              Region = NA)

hulu_originals_8 <- read_csv("../datasets/hulu/shows/table-8.csv")
hulu_originals_8 <- transmute(hulu_originals_8,
                              Title = Title,
                              Genre = Genre,
                              Premiere = Premiere,
                              Seasons = Seasons,
                              Runtime = Length,
                              Language = NA,
                              Status = Status,
                              Format = "Series",
                              Origin = "Original",
                              Network = `Partner / Country`,
                              Region = `Partner / Country`)

hulu_originals_9 <- read_csv("../datasets/hulu/shows/table-9.csv")
hulu_originals_9 <- transmute(hulu_originals_9,
                              Title = Title,
                              Genre = Genre,
                              Premiere = Premiere,
                              Seasons = Seasons,
                              Runtime = Length,
                              Language = NA,
                              Status = Status,
                              Format = "Series",
                              Origin = "Continuation",
                              Network = Network,
                              Region = NA)

hulu_originals_10 <- read_csv("../datasets/hulu/shows/table-10.csv")
hulu_originals_10 <- transmute(hulu_originals_10,
                              Title = Title,
                              Genre = Genre,
                              Premiere = Premiere,
                              Seasons = NA,
                              Runtime = Length,
                              Language = NA,
                              Status = "Event",
                              Format = "Special",
                              Origin = "Original",
                              Network = NA,
                              Region = NA)

hulu_originals_11 <- read_csv("../datasets/hulu/shows/table-11.csv")
hulu_originals_11 <- transmute(hulu_originals_11,
                              Title = Title,
                              Genre = Genre,
                              Premiere = Release,
                              Seasons = NA,
                              Runtime = Length,
                              Language = NA,
                              Status = ifelse(str_detect(Runtime, "TBA"), "Pending", "Ended"),
                              Format = "Film",
                              Origin = "Original",
                              Network = NA,
                              Region = NA)

hulu_originals_12 <- read_csv("../datasets/hulu/shows/table-12.csv")
hulu_originals_12 <- transmute(hulu_originals_12,
                              Title = Title,
                              Genre = "Documentary",
                              Premiere = Release,
                              Seasons = NA,
                              Runtime = Length,
                              Language = NA,
                              Status = "Ended",
                              Format = "Film",
                              Origin = "Original",
                              Network = NA,
                              Region = NA)

hulu_originals_13 <- read_csv("../datasets/hulu/shows/table-13.csv")
hulu_originals_13 <- transmute(hulu_originals_13,
                              Title = Title,
                              Genre = paste(Genre, " Drama"),
                              Premiere = Premiere,
                              Seasons = Seasons,
                              Runtime = Length,
                              Language = NA,
                              Status = "Pending",
                              Format = "Film",
                              Origin = "Original",
                              Network = NA,
                              Region = NA)

hulu_originals_14 <- read_csv("../datasets/hulu/shows/table-14.csv")
hulu_originals_14 <- transmute(hulu_originals_14,
                              Title = Title,
                              Genre = paste(Genre, " Comedy"),
                              Premiere = Premiere,
                              Seasons = Seasons,
                              Runtime = Length,
                              Language = NA,
                              Status = "Pending",
                              Format = "Film",
                              Origin = "Original",
                              Network = NA,
                              Region = NA)

hulu_originals_15 <- read_csv("../datasets/hulu/shows/table-15.csv")
hulu_originals_15 <- transmute(hulu_originals_15,
                              Title = Title,
                              Genre = paste(Genre, " Adult Animation"),
                              Premiere = Premiere,
                              Seasons = Seasons,
                              Runtime = Length,
                              Language = NA,
                              Status = "Pending",
                              Format = "Film",
                              Origin = "Original",
                              Network = NA,
                              Region = NA)

hulu_originals <- rbind(hulu_originals_1, hulu_originals_2)
hulu_originals <- rbind(hulu_originals, hulu_originals_3)
hulu_originals <- rbind(hulu_originals, hulu_originals_4)
hulu_originals <- rbind(hulu_originals, hulu_originals_5)
hulu_originals <- rbind(hulu_originals, hulu_originals_6)
hulu_originals <- rbind(hulu_originals, hulu_originals_7)
hulu_originals <- rbind(hulu_originals, hulu_originals_8)
hulu_originals <- rbind(hulu_originals, hulu_originals_9)
hulu_originals <- rbind(hulu_originals, hulu_originals_10)
hulu_originals <- rbind(hulu_originals, hulu_originals_11)
hulu_originals <- rbind(hulu_originals, hulu_originals_12)
hulu_originals <- rbind(hulu_originals, hulu_originals_13)
hulu_originals <- rbind(hulu_originals, hulu_originals_14)
hulu_originals <- rbind(hulu_originals, hulu_originals_15)

unique(select(hulu_originals, Status))

hulu_originals <- transmute(hulu_originals, 
                            Title = Title,
                            Genre = Genre,
                            Premiere = Premiere,
                            Seasons = Seasons,
                            Runtime = Runtime,
                            Language = Language,
                            Status = parse_factor(only_keep(Status, "(Renewed|Pending|Miniseries|Awaiting release|Event|Development|Ended|Film|Special|Distribution)"), levels = statuses),
                            Service = parse_factor("Hulu", levels = services),
                            Format = parse_factor(only_keep(Format, "(Series|Miniseries|Film|Special)"), levels = formats),
                            Origin = parse_factor(only_keep(Origin, "(Continuation|Distribution|Original)"), levels = origins),
                            Network = Network,
                            Region = Region)

hulu_originals
```