---
title: "netflix_transmutation"
author: "@grevend, @Fynn-Mehrens"
date: "13 12 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
```

## Importing from other Rmd file

```{r child = 'netflix_originals.Rmd'}
```

```{r}
netflix_originals <- netflix_originals
# netflix_originals <- read.csv("../datasets/netflix_originals.csv")
netflix_originals
```

## Transmutation of the given Netflix series and movie table

```{r}
anycharacter <- "([a-zA-Z]+)"

genres_to_uppercase <- function(genres) {
  curr <- ""
  all_genres <- ""
  c <- strsplit(genres, "")[[1]]
  for (i in 1:length(c)) {
    if (grepl(anycharacter, c[i])) {
      curr <- gsub(" ", "", str_squish(paste(curr, c[i])))
    }
    if (!grepl(anycharacter, c[i]) | i == length(c)) {
      if (i > 1 & grepl(anycharacter, c[i-1])) {
        whole_word = strsplit(curr, "")[[1]]
        single_genre <- ""
        for (j in 1:length(whole_word)) {
          if (j == 1) {
            single_genre <- gsub(" ", "", str_squish(toupper(whole_word[j])))
          } else {
            single_genre <- gsub(" ", "", str_squish(paste(single_genre, tolower(whole_word[j]))))
          }
        }
        if (i != length(strsplit(genres, "")[[1]])) {
          all_genres <- str_squish(paste(all_genres, single_genre, "/"))
        } else {
          all_genres <- paste(all_genres, single_genre)
        }
      }
      curr <- ""
    }
  }
  return(all_genres)
}
```


```{r}
netflix_originals <- filter(netflix_originals,
                            !grepl("Pending|pending", Title),
                            Title != "Awaiting release",
                            !grepl("Miniseries|miniseries", Title),
                            !grepl("Renewed|renewed", Title),
                            !grepl("due to premiere", Title))

transmuted <- transmute(netflix_originals, 
                                Title = Title,
                                Genre = str_replace_all(
                                          str_squish(
                                            str_replace_all(
                                              str_replace_all(
                                                str_replace_all(
                                                  str_replace_all(Genre, "series|procedural", ""),
                                                "Science fiction", "Science-Fiction"),
                                              "(C|c)oming-of-age ", ""),
                                            "(C|c)omedy-(D|d)rama", "Dramedy")
                                          ),
                                        "/| ", " / "),
                                Premiere = as.Date(str_replace_all(str_replace_all(Premiere, ",", ""), " ", "-"), "%B-%d-%Y"),
                                Episodes = strtoi(ifelse(!is.na(str_match(Seasons, "([0-9]+) (episode*)")[,2]),
                                                  str_match(Seasons, "([0-9]+) (episode*)")[,2],
                                                  NA)),
                                Seasons = strtoi(ifelse(!is.na(str_match(Seasons, "([0-9]) (season.*|part.*|volume.*)")[,2]),
                                                  str_match(Seasons, "([0-9]) (season.*|part.*|volume.*)")[,2],
                                                  NA)),
                                Min_Time = strtoi(ifelse(!is.na(str_match(Runtime, "([0-9]+)-([0-9]+)")[,2]),
                                                  str_match(Runtime, "([0-9]+)-([0-9]+)")[,2],
                                                  str_match(Runtime, "([0-9]+)")[,2])),
                                Max_Time = strtoi(ifelse(!is.na(str_match(Runtime, "([0-9]+)-([0-9]+)")[,3]),
                                                  str_match(Runtime, "([0-9]+)-([0-9]+)")[,3],
                                                  str_match(Runtime, "([0-9]+)")[,2])),
                                Language = Language,
                                Status = Status
                               )

transmuted
```

```{r}
string <- "23 min."

!is.na(str_match(string, "([0-9]+)-([0-9]+)")[,3])
str_match(string, "([0-9]+)")[,2]

matcher <- str_match(string, "([0-9]+)")
matcher
```

```{r}
string <- "2 seasons, 24 episodes"
!is.na(str_match(string, "([0-9])( season)"))
str_match(string, "([0-9])( season)")
```

